name: CD
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Auth to AWS using the IAM user keys you saved as secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Package your repo as a zip (must include appspec.yml + scripts)
      - name: Package app
        run: |
          mkdir -p bundle
          zip -qr bundle/revision.zip . -x ".git/*" ".github/*" "node_modules/*"

      # Upload to S3
      - name: Upload to S3
        run: |
          aws s3 cp bundle/revision.zip s3://${{ secrets.S3_BUCKET }}/revisions/${{ github.sha }}.zip

      # Register & trigger CodeDeploy deployment
      - name: Register application revision
        run: |
          aws deploy register-application-revision \
            --application-name "${{ secrets.CODEDEPLOY_APP }}" \
            --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=revisions/${{ github.sha }}.zip

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name "${{ secrets.CODEDEPLOY_APP }}" \
            --deployment-group-name "${{ secrets.CODEDEPLOY_GROUP }}" \
            --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=revisions/${{ github.sha }}.zip \
            --description "Deploy ${{ github.sha }} from ${{ github.repository }}"
