name: CI/CD
on:
  push:
    branches: [ main, add-tests-before-deploy ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # only runs if "test" job passes
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package app
        run: |
          mkdir -p bundle
          zip -qr bundle/revision.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Upload to S3
        run: |
          aws s3 cp bundle/revision.zip s3://${{ secrets.S3_BUCKET }}/revisions/${{ github.sha }}.zip

      - name: Register application revision
        run: |
          aws deploy register-application-revision \
            --application-name "${{ secrets.CODEDEPLOY_APP }}" \
            --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=revisions/${{ github.sha }}.zip

      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --application-name "${{ secrets.CODEDEPLOY_APP }}" \
            --deployment-group-name "${{ secrets.CODEDEPLOY_GROUP }}" \
            --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=revisions/${{ github.sha }}.zip \
            --description "Deploy ${{ github.sha }} from ${{ github.repository }}"

